### ISSUE TITLE
Bootstrap typeahead compatible ?

### ISSUE THREAD

**Issue by philmarc** [samirahmed/Zippopotamus-Cloud#1]
Since you're using jQuery UI autocomplete , I was wondering if I can use bootstrap typeahead instead ?
I tried to do it myself but I'm a beginner in JS.

```
$("#city").autocomplete({ source : ville , delay:50, disabled: false, minLength:0 });
$("#state").autocomplete({ source: region, delay:50 , disabled: false, minLength:0 });
```

Someone tried ?

**Comment by samirahmed** [comment]
I actually didn't try out bootstrap's typeahead and I don't know how it could be used, try using the dev tools in chrome/firefox to understand the example in the bootstrap sample 

http://twitter.github.com/bootstrap/javascript.html#typeahead

let us know if you can get it working

**Comment by instanceoftom** [comment]
This branch of the type ahead component should be relevant:
https://gist.github.com/1866577

It would need some tweaks to support the data structure you are providing but would be a good start.

**Comment by samirahmed** [comment]
@cykelfil  @instanceoftom did any of you figure out how to get to be compatible? It would be great if you share your solution!

**Comment by philmarc** [comment]
I unfortunatelly gave up on that one :(
