### ISSUE TITLE
Heroku?

### ISSUE THREAD

**Issue by stuartpb** [samirahmed/Zippopotamus-Cloud#11]
As long as your app doesn't need more than 1 concurrent process, you can host it on Heroku for free. (I'd submit a pull request, but I don't know what your pip dependencies are: see https://devcenter.heroku.com/articles/python for a guide to setting up Heroku-compatible Python apps.)

**Comment by samirahmed** [comment]
Its storage, we have about 1 million records that we need to store or the ridiculously priced mongo storage.

I will look into moving to heroku postgres.

**Comment by stuartpb** [comment]
What are the .stats() on your DB's collections?

**Comment by samirahmed** [comment]
```
{
    "db" : "zip",
    "collections" : 5,
    "objects" : 939063,
    "avgObjSize" : 219.2203334600554,
    "dataSize" : 205861704,
    "storageSize" : 266555392,
    "numExtents" : 28,
    "indexes" : 8,
    "indexSize" : 73379600,
    "fileSize" : 1006632960,
    "nsSizeMB" : 16,
    "ok" : 1
}
```

**Comment by stuartpb** [comment]
With a 960 MiB database like that, you could fit the DB on a [MongoLab "Small" shared plan](https://mongolab.com/products/pricing/) costing $10/mo (`heroku addons:add mongolab:small`). If that's too ridiculously priced, you could try optimizing your database's size by reducing the size of your fields (eg. using 'cc' instead of 'country abbreviation') and seeing if that would bring the fileSize to under 512MiB (which MongoLab will host for free with a Starter plan).

**Comment by samirahmed** [comment]
No, sorry for the oversight, that is certainly reasonable.  I will move it over to heroku asap

**Comment by samirahmed** [comment]
https://github.com/samirahmed/Zippopotamus-Cloud/blob/c1ded1d2e6eee02dd45e255534bb41b94c1002a8/README.md
