### ISSUE TITLE
crossdomain.xml

### ISSUE THREAD

**Issue by clarkenheim** [samirahmed/Zippopotamus-Cloud#7]
would you be able to add a crossdomain.xml file to the route of http://www.zippopotam.us/ to allow use from flash?

like so:

``` xml
<?xml version="1.0"?>
<cross-domain-policy>
  <allow-access-from domain="*" />
</cross-domain-policy>
```

or is there any particular reason why you wouldnt want people to use it from flash?

Thanks

**Comment by samirahmed** [comment]
we could do this - but are you sure that this would enable cross domain access?

If so feel free to make a pull request

**Comment by clarkenheim** [comment]
i am 100% sure that this will allow for cross domain access from flash applications. ;)

**Comment by samirahmed** [comment]
@clarkenheim can you confirm this worked?

**Comment by clarkenheim** [comment]
@samirahmed yea it worked great! thanks
